GET http://localhost:3000/jobs

###
GET http://localhost:3000/jobs/63e51728570e8a2dcdf94730


###
GET http://localhost:3000/jobs/63e518332f11d95818fb034f

###
DELETE http://localhost:3000/jobs/63e51728570e8a2dcdf94730

###
PATCH http://localhost:3000/jobs/63e518332f11d95818fb034f
Content-Type: application/json

{
    # be sure to double check the ',' when testing
    # to align with json format

    "contact": {
        "email": "newEmail@mail.com",
        "name": "new name"
        # passing a number is having a problem
        #"phone": 333
    },
    # "openingDate": "someDate",
    # "enteredBy": "Name A",
    # "updatedBy": "Name B",
    # "employer": "Some Company",
    # "industry": "Cafe",
    # "position": "Assisted Living",
    # "timeCommitment": "Full-Time",
    # "shift": "Afternoon",
    # issues with testing hourlyWafe because of type number
    # "hourlyWage": 10,
    # "benefits": "some benefits",
    # "notes": "some notes",
    # "address": "some street address",
    # "zip": "12345",
    # "city": "Some City",
    # "county": "Some County",
    # "createdAt": "Some Date", # needs to be in Date format
    # "updatedAt": "Some Date" #needs to be in Date format 
}