### get all jobs
GET http://localhost:3000/jobs

### get 1 job using id 63e51728570e8a2dcdf94730
GET http://localhost:3000/jobs/63e51728570e8a2dcdf94730


### get 1 job using id 63e518332f11d95818fb034f
GET http://localhost:3000/jobs/63e518332f11d95818fb034f

### delete 1 job using id 63e51728570e8a2dcdf94730
DELETE http://localhost:3000/jobs/63e51728570e8a2dcdf94730

### update 1 job using id 63e518332f11d95818fb034f
### the json below doesn't have to have every field, 
### just the ones client need to update.
PATCH http://localhost:3000/jobs/63e518332f11d95818fb034f
Content-Type: application/json

{
    # be sure to double check the ',' when testing
    # to align with json format

    "contact": {
        "email": "newEmail@mail.com",
        "name": "new name",
        "phone": 5000000000
    },
    # "openingDate": "someDate",
    # "enteredBy": "Name A",
    # "updatedBy": "Name B",
    # "employer": "Some Company",
    # "industry": "Cafe",
    # "position": "Assisted Living",
    # "timeCommitment": "Full-Time",
    # "shift": "Afternoon",
    # "hourlyWage": 10,
    # "benefits": "some benefits",
    # "notes": "some notes",
    # "address": "some street address",
    # "zip": "12345",
    # "city": "Some City",
    # "county": "Some County",
    # "createdAt": "Some Date", # needs to be in Date format
    # "updatedAt": "Some Date" # needs to be in Date format 
}

### the date format above shouldn't be an issue as
### they should have already been timestamped 
### and not manually entered by client